
sonar.projectKey=TuukkaUusitalo_proj_course_2_week_6
sonar.organization=tuukkauusitalo

sonar.host.url=https://localhost:9000

#sonar.sources=src/main/java
sonar.sources=src
sonar.tests=src/test/java
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.token=${env.SONAR_TOKEN}

sonar.java.binaries=target/classes

sonar.coverage.exclusions=\
src/main/java/org/example/MainController.java,\
src/main/java/org/example/FXApp.java,\
src/main/java/org/example/CartService.java,\
src/main/java/db/DatabaseInitializer.java,\
src/main/java/db/LocalizationService.java,\
src/main/java/db/DatabaseConnection.java,\
src/main/java/org/example/UTF8Control.java
